---
title: "Exploracao OD Tembici"
author: "Kaue"
date: '2022-04-11'
output:
  pdf_document: default
  html_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, error = FALSE, message = FALSE)

library(readr)
library(dplyr)
library(data.table)
library(readr)
library(sf)
library(googlesheets4)
library(hrbrthemes)
library(ggplot2)
library(mapview)
ss <- "https://docs.google.com/spreadsheets/d/1IhrcEZCJuNib5Xlvn-LhVnhyUITZ0YyM5NGyLBVqm_A/edit#gid=0"
mapviewOptions(fgb = FALSE)

rio_limits <- geobr::read_municipality(3304557) %>% st_transform(4326)
```

Tratamento:

```{r tratamento, cache=TRUE}

# open ttmatrix
ttmatrix <- readr::read_rds("../../data/smtr_malha_cicloviaria/1-ttmatrix_od/ttmatrix_detailed_rio_bike.rds")
ttmatrix <- ttmatrix %>% select(initial_station_name = fromId, final_station_name = toId, 
                                # ttime_r5r = total_duration,
                                dist = distance)
# open OD
od_bike <- fread("../../data-raw/smtr_malha_cicloviaria/bike_trips/trips_BikeRio_20210901.csv")
# separar entre semana e final de semana
od_bike[, dia := as.Date(start_time)]
od_bike[, duration := round(duration_seconds/60)]
od_bike[, start_hour := hour(start_time)]
od_bike[, weekday := lubridate::wday(dia)]
od_bike[, day_type := fifelse(weekday %in% c(1, 2, 3, 4, 5), "semana", "final_de_semana")]
# fazr pico - fora pco
od_bike[, hour_type := fifelse(start_hour %in% c(6, 7), "pico_manha",
                               fifelse(start_hour %in% c(16, 17), "pico_tarde",
                                       fifelse(start_hour %in% c(14, 15), "fora_pico", "vale")))]

# apagar viagens com menos de 2 minutos
od_bike <- od_bike[duration >= 2]

# agrupar OD por rota
agrupar_od_por_rota <- function(od) {
  
  # trazer as rotas para o arquivo de ttmatrix
  od_rota <- od %>%
    # get unique OD
    # filter(initial_station_name != final_station_name) %>%
    group_by(initial_station_name, final_station_name, day_type, hour_type) %>%
    summarise(trips_n = n(), duration = round(mean(duration))) %>%
    # , ttime_bike = mean(ttime)) %>% 
    ungroup() %>%
    arrange(desc(trips_n)) %>%
    # deletar origem = destino
    # trazer as rotas!
    left_join(ttmatrix, by = c("initial_station_name", "final_station_name")) %>%
    st_sf()
  
}

od_bike_group <- agrupar_od_por_rota(od_bike)

# identificar viagens de entregadores
# para cada estacao, tambem considerar outras estacoes num raio de 300 metros
estacoes <- od_bike[, .(lon = first(initial_station_longitude), lat = first(initial_station_latitude)),
                       by = .(initial_station_name)]
estacoes <- estacoes %>% st_as_sf(coords = c("lon", "lat"), crs = 4326)

# salvar
st_write(estacoes, "../../data/smtr_malha_cicloviaria/explore_od_tembici/estacoes_tembici.gpkg")

identificar_estacoes_vizinhas <- function(estacao) {
  # estacao <- "14 - Pereira da Silva"
  
  estacoes1 <- estacoes %>% filter(initial_station_name == estacao)
  # distance to all other stations
  estacoes_dist <- st_distance(estacoes1, estacoes) %>% as.numeric()
  # input dist
  estacoes_fim <- estacoes %>% 
    mutate(estacao_from = estacoes1$initial_station_name) %>%
    mutate(dist = estacoes_dist) %>%
    # pegar somente menor que 200 metros
    filter(dist <= 300) %>%
    st_set_geometry(NULL) %>%
    setDT()
}

estacoes_dist <- lapply(estacoes$initial_station_name, identificar_estacoes_vizinhas) %>%
  rbindlist()

# criar coluna unica
estacoes_dist1 <- estacoes_dist[, .(vizinhos = paste0(initial_station_name, collapse = "|")), by = estacao_from ]

# incorporar a matriz agrupada
od_bike_group <- left_join(od_bike_group, estacoes_dist1, by = c("initial_station_name" = "estacao_from"))

# criar coluna com identificacao se eh entregador ou nao
od_bike_group <- od_bike_group %>% mutate(entregador = ifelse(stringr::str_detect(final_station_name, vizinhos), TRUE, FALSE)) 
  

```


## Quantidade de viagens por dia

```{r viagens_dia}

viagens_dia <- od_bike[, .(N = .N, day_type = first(day_type)), by = dia]
setorder(viagens_dia, dia)

write_sheet(data = viagens_dia,
            ss = ss,
            sheet = "Viagens por dia")

graph_trips_dia <- ggplot()+
  geom_col(data = viagens_dia, aes(x = dia, y = N, fill = day_type)) +
  theme_bw()+
  theme(legend.position = "bottom")+
  labs(title = "Viagens por dia - Setembro/2021",
       x = "Dia",
       y = "Quantidade")

# salvar
ggsave(plot = graph_trips_dia, filename = "figures/explore_od/1-graph_trips_dia.png",
       width = 16, height = 10, units = "cm")



```

## Quantidades de viagem por hora

```{r viagens_hora}

viagens_hora <- od_bike[, .(N = .N), by = .(start_hour, day_type)]
setorder(viagens_hora, day_type, start_hour)

# sumary
a <- viagens_hora[day_type == "semana"]
a %>% mutate(total = sum(N)) %>% group_by(start_hour) %>% mutate(perc = N / total)

write_sheet(data = viagens_hora,
            ss = ss,
            sheet = "Viagens por hora")

graph_trips_hora <- ggplot()+
  geom_col(data = viagens_hora, aes(x = as.factor(start_hour), y = N)) +
  scale_x_discrete(breaks = c(1:24))+
  facet_wrap(~day_type) +
  theme_bw()+
  theme(legend.position = "bottom")+
  labs(title = "Viagens por hora - Setembro/2021",
       x = "Hora",
       y = "Quantidade")

# salvar
ggsave(plot = graph_trips_hora, filename = "figures/explore_od/2-graph_trips_hora.png",
       width = 16, height = 10, units = "cm")

```

## Duração das viagens

```{r viagens_duracao}

# primeiro, excluir viagens com menos de 2 minutos, q podem ser problematicas
od_bike1 <- od_bike[duration >= 2]

od_bike1[, duracao_break := cut(duration, 
                                breaks = c(0, 10, 20, 30, 40, 50, 60, 90, Inf),
                                labels = c("0-10", "10-20", "20-30", "30-40", "40-50", "50-60", "60-90", "90+")
)]
trips_duracao <- od_bike1[, .N, by = .(duracao_break, day_type)]
trips_duracao[, total := sum(N), by = day_type]
trips_duracao[, perc := N/total]
trips_duracao$day_type <- factor(trips_duracao$day_type, 
                                 levels = c("semana", "final_de_semana"))

a <- trips_duracao %>% 
  arrange(duracao_break, day_type)
# setorder(viagens_hora, day_type, start_hour)

# write_sheet(data = viagens_hora,
#             ss = ss,
#             sheet = "Viagens por hora")

graph_trips_duracao <- ggplot()+
  geom_col(data = trips_duracao, aes(x = as.factor(duracao_break), y = N)) +
  facet_wrap(~day_type, scales = "free") +
  theme_bw()+
  theme(legend.position = "bottom")+
  labs(title = "Histograma da duração das viagens - Setembro/2021",
       x = "Minutos",
       y = "Quantidade")

# salvar
ggsave(plot = graph_trips_duracao, filename = "figures/explore_od/3-graph_trips_duracao.png",
       width = 16, height = 10, units = "cm")

```

## Quantidade de viagens por estacao por hora - origem

```{r viagens_estacao}

viagens_estacao <- od_bike[, .(N = .N), by = .(initial_station_name, start_hour, day_type)]
setorder(viagens_estacao, -N, day_type, start_hour)

write_sheet(data = viagens_estacao,
            ss = ss,
            sheet = "Viagens por estacao e hora")

# ggplot()+
#   geom_col(data = viagens_hora, aes(x = as.factor(start_hour), y = N)) +
#   scale_x_discrete(breaks = c(1:24))+
#   facet_wrap(~day_type) +
#   theme_bw()+
#   theme(legend.position = "bottom")+
#   labs(title = "Viagens por hora - Setembro/2021",
#        x = "Hora",
#        y = "Quantidade")

```

## Quantidade de viagens por cada par OD

```{r viagens_par_od, cache = TRUE}

# quantidade de viagens total
od_total <- od_bike_group %>%
  st_set_geometry(NULL) %>%
  group_by(initial_station_name, final_station_name) %>%
  summarise(trips_n = sum(trips_n), entregador = first(entregador)) %>%
  ungroup() %>%
  arrange(desc(trips_n))



# quantidade de viagens diarias por pico-fora pico
od_pico_manha_semana <- od_bike_group %>% filter(day_type == "semana", hour_type == "pico_manha") %>%
  arrange(desc(trips_n))
od_pico_tarde_semana <- od_bike_group %>% filter(day_type == "semana", hour_type == "pico_tarde") %>%
  arrange(desc(trips_n))
# quantidade de viagens diarias por pico-fora pico
od_fpico_semana <- od_bike_group %>% filter(day_type == "semana", hour_type == "fora_pico") %>%
  arrange(desc(trips_n))
# quantidade de viagens diarias por final de semana
od_fsemana <- od_bike_group %>% filter(day_type == "final_de_semana") %>%
  st_set_geometry(NULL) %>%
  group_by(initial_station_name, final_station_name, day_type) %>%
  summarise(trips_n = sum(trips_n)) %>%
  arrange(desc(trips_n)) %>%
  ungroup() %>%
  left_join(od_bike_group %>% distinct(initial_station_name, final_station_name))

file.remove("../../data/smtr_malha_cicloviaria/explore_od_tembici/viagens_por_od/viagens_od_pico_manha_semana.gpkg")
file.remove("../../data/smtr_malha_cicloviaria/explore_od_tembici/viagens_por_od/viagens_od_pico_tarde_semana.gpkg")
file.remove("../../data/smtr_malha_cicloviaria/explore_od_tembici/viagens_por_od/viagens_od_fpico_semana.gpkg")

st_write(od_pico_manha_semana, "../../data/smtr_malha_cicloviaria/explore_od_tembici/viagens_por_od/viagens_od_pico_manha_semana.gpkg", append = FALSE)

st_write(od_pico_tarde_semana, "../../data/smtr_malha_cicloviaria/explore_od_tembici/viagens_por_od/viagens_od_pico_tarde_semana.gpkg", append = FALSE)

st_write(od_fpico_semana, "../../data/smtr_malha_cicloviaria/explore_od_tembici/viagens_por_od/viagens_od_fpico_semana.gpkg", append = FALSE)

# st_write(od_fsemana, "../../data/smtr_malha_cicloviaria/explore_od_tembici/viagens_por_od/viagens_od_fsemana.gpkg")

# salvar uma amostra no googlesheets
write_sheet(data = od_total %>% slice(1:100),
            ss = ss,
            sheet = "Viagens por OD - Total")
write_sheet(data = od_pico_manha_semana %>% st_set_geometry(NULL) %>% slice(1:100),
            ss = ss,
            sheet = "Viagens por OD - Pico manhã semana")
write_sheet(data = od_pico_tarde_semana %>% st_set_geometry(NULL) %>% slice(1:100),
            ss = ss,
            sheet = "Viagens por OD - Pico tarde semana")
write_sheet(data = od_fpico_semana %>% st_set_geometry(NULL) %>% slice(1:100),
            ss = ss,
            sheet = "Viagens por OD - ForaPico semana")


ggplot()+
  geom_sf(data = rio_limits, fill = NA, color = "grey85")+
  geom_sf(data = od_pico_semana %>% slice(1:100), alpha = 0.8)+
  labs(title = "Pares OD com mais viagens - Pico Semana - Top 100") +
  theme_void()

ggplot()+
  geom_sf(data = rio_limits, fill = NA, color = "grey85")+
  geom_sf(data = od_fpico_semana %>% slice(1:100), alpha = 0.8)+
  labs(title = "Pares OD com mais viagens - Fora Pico Semana - Top 100") +
  theme_void()


```

## Identificando entregadores

```{r entregadores}


# identificar entregadores: mesma origm e destino ---------------------------------------------
od_bike_entregadores <- od_bike %>%
  filter(initial_station_name == final_station_name) %>%
  # pegar somente com mais de 5 minutos
  filter(duration >= 5) %>%
  # agrupar
  group_by(initial_station_name, final_station_name) %>%
  summarise(trips_n = n(), duration = mean(duration)) %>%
  ungroup() %>%
  arrange(desc(trips_n)) %>%
  select(initial_station_name, trips_n, duration) %>%
  # trazer localizacao das estacoes
  left_join(od_bike %>% distinct(initial_station_name, .keep_all = TRUE) %>%
              select(initial_station_name, 
                     lon = initial_station_longitude,
                     lat = initial_station_latitude),
            by = "initial_station_name") %>%
  st_as_sf(coords = c("lon", "lat")) %>%
  st_sf(crs = 4326)

file.remove("../../data/smtr_malha_cicloviaria/explore_od_tembici/od_bike_entregadores.gpkg")

st_write(od_bike_entregadores, "../../data/smtr_malha_cicloviaria/explore_od_tembici/od_bike_entregadores.gpkg")


write_sheet(data = od_bike_entregadores %>% st_set_geometry(NULL) %>% slice(1:100),
            ss = ss,
            sheet = "Viagens com origem = destino")

ggplot()+
  geom_sf(data = rio_limits, fill = NA)+
  geom_sf(data = od_bike_entregadores, aes(size = trips_n), alpha = 0.3)+
  labs(title = "Estacoes com origem = destino") +
  theme_void()


```

## Viagens proximo a estacoes de transporte

```{r viagens_estacoes1}


# abrir estacoes
estacoes <- geojsonsf::geojson_sf("../../data-raw/smtr_malha_cicloviaria/Estacoes_mediaalta_transporte.geojson")
estacoes <- st_zm(estacoes)
estacoes <- st_set_crs(estacoes, 32723)
estacoes <- st_transform(estacoes, 4326)
estacoes <- estacoes %>%
  mutate(station_id = 1:n()) %>%
  select(station_id, Station = Nome)


# buffer das estacoes
estacoes_buffer <- st_transform(estacoes, crs = 31983) %>%
  st_buffer(dist = 300) %>%
  st_transform(crs = 4326)

ggplot()+
  geom_sf(data = rio_limits, fill = NA)+
  geom_sf(data = estacoes_buffer, alpha = 0.3)+
  labs(title = "Estacoes de média/alta capacidade - buffer") +
  theme_void()

# viagens de origem 
od_bike_origem_sf <- od_bike %>% 
  select(trip_id, initial_station_name, lon = initial_station_longitude, lat = initial_station_latitude) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

# mapview(estacoes_buffer) + od_bike_origem_sf[1:100,]

# join
od_bike_origem_sf <- od_bike_origem_sf %>%
  st_join(estacoes_buffer)

od_bike_origem_sf <- od_bike_origem_sf %>%
  mutate(perto_estacao = ifelse(is.na(station_id), "nao", "sim"))

estacoes_origem_transporte <- od_bike_origem_sf %>%
  st_set_geometry(NULL) %>%
  filter(perto_estacao == "sim") %>%
  count(station_id, Station) %>%
  arrange(desc(n)) %>%
  # trazer localizacao das estacoes
  left_join(select(estacoes, station_id), by = "station_id") %>%
  st_sf(crs = 4326)

file.remove("../../data/smtr_malha_cicloviaria/explore_od_tembici/estacoes_origem_transporte.gpkg")
st_write(estacoes_origem_transporte, "../../data/smtr_malha_cicloviaria/explore_od_tembici/estacoes_origem_transporte.gpkg")

ggplot()+
  geom_sf(data = rio_limits, fill = NA)+
  geom_sf(data = estacoes_origem_transporte, aes(size = n, alpha = n))+
  labs(title = "Estacoes com viagens em sua área de influência") +
  theme_void()

write_sheet(data = estacoes_origem_transporte %>% st_set_geometry(NULL),
            ss = ss,
            sheet = "Quantidade perto de estações de transporte")

# prop.table(table(od_bike_origem_sf$perto_estacao))

# viagens de destino 
od_bike_destino_sf <- od_bike %>% 
  select(trip_id, final_station_name, lon = final_station_longitude, lat = final_station_latitude) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

# join
od_bike_destino_sf <- od_bike_destino_sf %>%
  st_join(estacoes_buffer)

od_bike_destino_sf <- od_bike_destino_sf %>%
  mutate(perto_estacao = ifelse(is.na(station_id), "nao", "sim")) 

# prop.table(table(od_bike_destino_sf$perto_estacao))

# juntar com a matriz original
od_bike <- od_bike %>%
  left_join(od_bike_origem_sf %>% st_set_geometry(NULL) %>% distinct(trip_id, perto_estacao),
            by = "trip_id") %>%
  left_join(od_bike_destino_sf %>% st_set_geometry(NULL) %>% distinct(trip_id, perto_estacao),
            by = "trip_id") %>%
  mutate(perto_estacao = ifelse(perto_estacao.x == "sim" | perto_estacao.y == "sim", "sim", "nao"))

prop.table(table(od_bike$perto_estacao))


```
